# Generated by Django 4.2.4 on 2023-09-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_task_project_section_task_secion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
