# Generated by Django 4.2.4 on 2023-09-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_task_creator_label'),
        ('panel', '0008_project_members_project_owner_section_project'),
    ]

    operations = [
    ]
