# Generated by Django 4.2.7 on 2023-12-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_merge_20230907_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='creator',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(max_length=50),
        ),
    ]
